import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import TopbarMenu from "@/components/ui/topbar-menu";
import { cn } from "@/lib/utils";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" /*className={cn("font-sans", inter.variable)}*/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-260 m-auto">
          <TopbarMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
